enableMirror: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-berry.js
